map_type: costmap
transform_tolerance: 2.0
obstacle_range: 2.5
raytrace_range: 3.0
footprint: [ [0.254, -0.0508], [0.1778, -0.0508], [0.1778, -0.1778], [-0.1905, -0.1778], [-0.254, 0], [-0.1905, 0.1778], [0.1778, 0.1778], [0.1778, 0.0508], [0.254, 0.0508] ]

#Footprint with rear laser scanner
#footprint: [[0.26, 0.18],[0.26, 0.014],[0.31, 0.014],[0.31, -0.014],[0.26, -0.014],[0.26, -0.18],[-0.27, -0.18],[-0.27,-0.014],[-0.32,-0.014],
#[-0.32,0.014],[-0.27,0.014],[-0.27, 0.18]]

inflation_radius: 5.0

observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: lms100, data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 0.2}

#obstacle_layer:
#  observation_sourses: laser_scan_sensor
#  laser_scan_sensor: {sensor_frame: lms100, data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 0.2}
