
recovery_behaviors: [{
    name: semantic_recovery_behavior, 
    type: semantic_clear_costmap_recovery/SemanticClearCostmapRecovery
  }]

#Footprint with rear laser
footprint: [ [0.254, -0.0508], [0.1778, -0.0508], [0.1778, -0.1778], [-0.1905, -0.1778], [-0.254, 0], [-0.1905, 0.1778], [0.1778, 0.1778], [0.1778, 0.0508], [0.254, 0.0508] ]
controller_frequency: 10.0
planner_frequency: 1.0
controller_patience: 15.0
clearing_radius: 0.25
footprint_padding: 0.03
clearing_rotation_allowed: false
oscillation_distance: 2.0
shutdown_costmaps: true
